{"name": "test_answer", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 5\n +  where 4 = inc(3)", "trace": "def test_answer():\n>       assert inc(3) == 5\nE       assert 4 == 5\nE        +  where 4 = inc(3)\n\ntest_sample.py:6: AssertionError"}, "start": 1531733224483, "stop": 1531733224486, "uuid": "a9cebfcd-8291-4fbf-b584-1f92d513ed76", "historyId": "c398165193b396d834e5e030605bc655", "fullName": "test_sample#test_answer", "labels": [{"name": "host", "value": "4d2532c89c27"}, {"name": "thread", "value": "675-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_sample"}]}